feat: new modules, fixes, and error handling
debionetwork/polkadot-provider pull request #60
Opened 2022-06-02 17:41 UTC by agustinustheo

### JIRA LINK
- https://blocksphere2020.atlassian.net/browse/DBIO-2556
- https://blocksphere2020.atlassian.net/browse/DBIO-2575
- https://blocksphere2020.atlassian.net/browse/DBIO-2594

### Changelog
- Fix typo.
- Fix type.
- Error handling using promises.
- Doctor certifications pallet and integration tests.
- Hospital certifications pallet and integration tests.

2022-06-02 18:26 UTC, agustinustheo commented
Waiting for updates from @azmimuhammad

2022-06-02 22:23 UTC, agustinustheo commented
![image](https://user-images.githubusercontent.com/37565691/171748088-5a574afa-792a-478f-af58-ea093af2f22c.png)
Tests successful

2022-06-03 07:41 UTC, agustinustheo commented
![image](https://user-images.githubusercontent.com/37565691/171810340-c6fc1cf1-a2d0-4562-a71d-5ff964fdc543.png)

All successful. No errors for now

2022-06-03 08:06 UTC, JackyRahman approved these changes

2022-06-03 08:17 UTC, ciniiia requested changes
Please add functions for `stakeLabFee` and `unstakeLabFee` and change `geneticAnalysisIdTrackingId` to `geneticAnalysisTrackingId`

2022-06-03 08:17 UTC, ciniiia commented on src/command/labs/index.ts
>  }
please add functions for stakeLabFee and unstakeLabFee

2022-06-03 08:17 UTC, ciniiia commented on src/models/genetic-analysts/genetic-analysis-orders/index.ts
> +    this.geneticAnalysisIdTrackingId = anyJson.geneticAnalysisTrackingId;
typo ? `geneticAnalysisTrackingId`

2022-06-03 08:17 UTC, ciniiia commented on src/models/genetic-analysts/genetic-analysis-orders/index.ts
> +  geneticAnalysisIdTrackingId: string;
typo ? `geneticAnalysisTrackingId`

2022-06-03 08:17 UTC, ciniiia commented on test/e2e/genetic-analysts/genetic-analysis-order.spec.ts
> +      geneticAnalysisOrder.geneticAnalysisIdTrackingId,
`geneticAnalysisTrackingId`

2022-06-03 08:17 UTC, ciniiia commented on test/e2e/genetic-analysts/genetic-analysis-order.spec.ts
> +      geneticAnalysisOrder.geneticAnalysisIdTrackingId,
`geneticAnalysisTrackingId`

2022-06-03 08:17 UTC, ciniiia commented on test/e2e/genetic-analysts/genetic-analysis-order.spec.ts
> +      _geneticAnalysisOrder.geneticAnalysisIdTrackingId,
`geneticAnalysisTrackingId`

2022-06-03 08:17 UTC, ciniiia commented on test/e2e/genetic-analysts/genetic-analysis-order.spec.ts
> +      _geneticAnalysisOrder.geneticAnalysisIdTrackingId,
`geneticAnalysisTrackingId`

2022-06-03 08:17 UTC, ciniiia commented on test/e2e/genetic-analysts/genetic-analysis.spec.ts
> +      submitGeneticAnalysis(api, pair, geneticAnalysisOrder.geneticAnalysisIdTrackingId, geneticDataMock.reportLink, "string", () => {
`geneticAnalysisTrackingId`

2022-06-03 08:17 UTC, ciniiia commented on test/e2e/genetic-analysts/genetic-analysis.spec.ts
> +        queryGeneticAnalysisByGeneticAnalysisTrackingId(api, geneticAnalysisOrder.geneticAnalysisIdTrackingId)
`geneticAnalysisTrackingId`

2022-06-03 08:24 UTC, ciniiia approved these changes
LGTM!

2022-06-03 08:58 UTC, agustinustheo commented
![image](https://user-images.githubusercontent.com/37565691/171823134-3339ac20-a707-49b7-950c-a4e8af7760af.png)

All tests are passing again.

2022-06-03 08:59 UTC, merged