feat: Add polkadot provider event handler
debionetwork/polkadot-provider pull request #66
Opened 2022-06-27 07:20 UTC by bukandicki

### JIRA LINK
- https://blocksphere2020.atlassian.net/browse/DBIO-2720

### Changelog
- Add polkadot provider event handler
- Add unit testing event handler

2022-06-27 10:18 UTC, agustinustheo requested changes
You don't need to mock the data samples, use the ones from the frontend directly.

2022-06-27 10:30 UTC, bukandicki commented
> You don't need to mock the data samples, use the ones from the frontend directly.

Ok, will update ASAP

2022-06-28 17:38 UTC, agustinustheo requested changes

2022-06-28 17:38 UTC, agustinustheo commented on src/events/handlers/customer.ts
> +
Please unit test the handlers too.

2022-07-04 08:37 UTC, agustinustheo approved these changes

2022-07-04 08:38 UTC, merged